/// <reference types="next" />
/// <reference types="react" />
/// <reference types="react-dom" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js.
